### ISSUE TITLE
Exception inserting regex in Blacklist_p.html

### ISSUE THREAD

**Issue by davidebaldini** [yacy/yacy_search_server#160]
In the page Blacklist_p.html an exception is thrown if I submit this regex to the "Add new pattern" form:

    ^(http.?://)?[^/]*\b(?!en)..\..*

while the same regex is handled fine from the page RegexTest.htm.

This is the message I get from the exception:

```
Ops!

Message: /home/user/yacy/htroot/Blacklist_p.html
javax.servlet.ServletException: /home/user/yacy/htroot/Blacklist_p.html
	at net.yacy.http.servlets.YaCyDefaultServlet.handleTemplate(YaCyDefaultServlet.java:910)
	at net.yacy.http.servlets.YaCyDefaultServlet.doGet(YaCyDefaultServlet.java:315)
	at net.yacy.http.servlets.YaCyDefaultServlet.doPost(YaCyDefaultServlet.java:377)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:513)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:190)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at net.yacy.http.CrashProtectionHandler.handle(CrashProtectionHandler.java:33)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:530)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:347)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

### Versions
JVM: Openjdk 9
Yacy taken from commit https://github.com/yacy/yacy_search_server/commit/fa65fb1a03adbeaf5a804ffa67ed17b014a47ab1

**Comment by luccioman** [comment]
Hi @davidebaldini , I also reproduce the same error as you with OpenJDK8.
To my mind, regex parsing exception has indeed to be handled more properly. 

But I also think the "a complete regular expression" label is a bit excessive and confusing. 

The current YaCy blacklist parsing implementation, indeed always needs expressions with a clearly identified host part and a path part, separated with a "/" character.
So you would probably need to refactor your expression a bit : indeed the `^(http.?://)?[^/]* ` part is unnecessary and confuses the parser.
Would you like to provide some example URLs you want to be blacklisted by your pattern?

**Comment by davidebaldini** [comment]
That regex is meant to match any URL with a two-letter component in its domain or subdomain different from the country code "en". Domains without a two-letter (sub-)domain component are not matched.

> always needs expressions with a clearly identified host part and a path part, separated with a "/" character

If both those parts can be a regex than that would be good, as my intention here is to have a regex match on the domain itself, not the path.

I won't be testing a new regex soon, but I'll report back in case of further problems.

**Comment by luccioman** [comment]
Your blacklist entry rewritten as `.*\b(?!en)..\..*/.*` seems to do the job if I understand correctly your idea. Some examples :
- http://fr.example.org/ : blocked
- http://franck.example.org/ : not blocked
- http://en.example.org/ : not blocked
- http://en.example.org/fr.html : not blocked

**Comment by davidebaldini** [comment]
If this slash

    .*\b(?!en)..\..*/.*
                    ^

is interpreted by Yacy as a separator between the left part and the right part of the regex, and each part is independently used to match against the hostname and the path respectively, your regex would be fine; though this would be a peculiar way for Yacy to handle a regex.

I cannot test the regex on Yacy now, but I guess that solves my problem. Maybe this ticked could stay open if you think something should be improved in this area.

**Comment by luccioman** [comment]
@davidebaldini , although YaCy generally handles regular expressions in a standard way, this specific behavior is directly linked to how blacklist entries are internally stored and processed.

I close this issue as I hope last commits will make this aspect more clear and usable from a user point of view. Of course the blacklist editor itself has room for improvement, but it goes beyond this specific issue.

By the way, thanks for reporting, I let you open another ticket if you encounter other problems.
