### ISSUE TITLE
IndexControlURLs_p.html HTTP ERROR 400 when clicking Show Details for URL button

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#205]
> HTTP ERROR 400
> Problem accessing /solr/select. Reason:
> 
>     org.apache.solr.search.SyntaxError: Cannot parse 'crawldepth_i:0^.4': Lexical error at line 1, column 16.  Encountered: "." (46), after : ""
> 
> org.apache.solr.common.SolrException: org.apache.solr.search.SyntaxError: Cannot parse 'crawldepth_i:0^.4': Lexical error at line 1, column 16.  Encountered: "." (46), after : ""
> 	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:219)
> 	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:270)
> 	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
> 	at net.yacy.cora.federate.solr.connector.EmbeddedSolrConnector.query(EmbeddedSolrConnector.java:219)
> 	at net.yacy.http.servlets.SolrSelectServlet.service(SolrSelectServlet.java:266)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:857)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
> 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)

**Comment by luccioman** [comment]
@songproducer I could not reproduce the issue on a YaCy node running from latest sources.
Does the problem occurs on any URL entered in the 'Retrieve by URL:' field? Or can you tell which value you entered in that field that triggers the issue?
