### ISSUE TITLE
ConfigHeuristics_p.html won't load

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#209]
I added a couple open search providers (wordpress and data citations) and now I can't load the Config Hueristics page.

> Ops!
> 
> Message: /home/leo/yacy_search_server/htroot/ConfigHeuristics_p.html
> javax.servlet.ServletException: /home/leo/yacy_search_server/htroot/ConfigHeuristics_p.html
> 	at net.yacy.http.servlets.YaCyDefaultServlet.handleTemplate(YaCyDefaultServlet.java:909)
> 	at net.yacy.http.servlets.YaCyDefaultServlet.doGet(YaCyDefaultServlet.java:315)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
> 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
> 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
> 	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
> 	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
> 	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
> 	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
> 	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
> 	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
> 	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
> 	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
> 	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> 	at net.yacy.http.CrashProtectionHandler.handle(CrashProtectionHandler.java:33)
> 	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
> 	at org.eclipse.jetty.server.Server.handle(Server.java:531)
> 	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
> 	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
> 	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
> 	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
> 	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
> 	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
> 	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
> 	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
> 	at java.lang.Thread.run(Thread.java:748)

**Comment by songproducer** [comment]
Log file shows this:
```
I 2018/08/05 17:29:16 EmbeddedSolrConnector.getResponseByParams QUERY: q=vocabularies_sxt:[* TO *]&rows=0&start=0&facet=true&facet.mincount=1&facet.limit=100&facet.sort=count&facet.method=enum&fl=vocabularies_sxt&facet.field=vocabularies_sxt
I 2018/08/05 17:29:16 EmbeddedSolrConnector.getResponseByParams QUERY: q=*:*&rows=0&start=0&facet=true&facet.mincount=1&facet.limit=100&facet.sort=count&facet.method=enum&fl=vocabulary_English Wikipedia_log_i,vocabulary_Stadtthemen_log_i,vocabulary_frompagetitle_log_i,vocabulary_new_log_i,vocabulary_Locations_log_i,vocabulary_English Wikipedia_log_val,vocabulary_Stadtthemen_log_val,vocabulary_frompagetitle_log_val,vocabulary_new_log_val,vocabulary_Locations_log_val&facet.field=vocabulary_English Wikipedia_log_i&facet.field=vocabulary_Stadtthemen_log_i&facet.field=vocabulary_frompagetitle_log_i&facet.field=vocabulary_new_log_i&facet.field=vocabulary_Locations_log_i&facet.field=vocabulary_English Wikipedia_log_val&facet.field=vocabulary_Stadtthemen_log_val&facet.field=vocabulary_frompagetitle_log_val&facet.field=vocabulary_new_log_val&facet.field=vocabulary_Locations_log_val
I 2018/08/05 17:29:17 EmbeddedSolrConnector.getResponseByParams QUERY: q=vocabularies_sxt:[* TO *]&rows=0&start=0&facet=true&facet.mincount=1&facet.limit=100&facet.sort=count&facet.method=enum&fl=vocabularies_sxt&facet.field=vocabularies_sxt
I 2018/08/05 17:29:17 EmbeddedSolrConnector.getResponseByParams QUERY: q=*:*&rows=0&start=0&facet=true&facet.mincount=1&facet.limit=100&facet.sort=count&facet.method=enum&fl=vocabulary_English Wikipedia_log_i,vocabulary_Stadtthemen_log_i,vocabulary_frompagetitle_log_i,vocabulary_new_log_i,vocabulary_Locations_log_i,vocabulary_English Wikipedia_log_val,vocabulary_Stadtthemen_log_val,vocabulary_frompagetitle_log_val,vocabulary_new_log_val,vocabulary_Locations_log_val&facet.field=vocabulary_English Wikipedia_log_i&facet.field=vocabulary_Stadtthemen_log_i&facet.field=vocabulary_frompagetitle_log_i&facet.field=vocabulary_new_log_i&facet.field=vocabulary_Locations_log_i&facet.field=vocabulary_English Wikipedia_log_val&facet.field=vocabulary_Stadtthemen_log_val&facet.field=vocabulary_frompagetitle_log_val&facet.field=vocabulary_new_log_val&facet.field=vocabulary_Locations_log_val
W 2018/08/05 17:29:18 ConcurrentLog java.lang.reflect.InvocationTargetException
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.yacy.http.servlets.YaCyDefaultServlet.invokeServlet(YaCyDefaultServlet.java:672)
	at net.yacy.http.servlets.YaCyDefaultServlet.handleTemplate(YaCyDefaultServlet.java:881)
	at net.yacy.http.servlets.YaCyDefaultServlet.doGet(YaCyDefaultServlet.java:315)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:865)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:724)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:524)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1317)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1219)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at net.yacy.http.CrashProtectionHandler.handle(CrashProtectionHandler.java:33)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.eclipse.jetty.server.Server.handle(Server.java:531)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:762)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:680)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at ConfigHeuristics_p.respond(ConfigHeuristics_p.java:209)
	... 43 more

```

**Comment by luccioman** [comment]
Hello @songproducer , I also reproduce the issue when I enter an empty URL value for a line in the "Available/Active Opensearch" System table. In the DATA/SETTINGS/heuristicopensearch.conf file, this results in a line like `title  #Comment`, instead of `title = http://fullUrl  #comment`.
Waiting for a proper fix, you should be able to solve your issue by manually checking this file and editing the wrong lines.

**Comment by luccioman** [comment]
A fix is also now available if you upgrade to latest sources on GitHub.

**Comment by songproducer** [comment]
@luccioman thanks! How can I upgrade to latest sources without losing my index? Do I just move the folder DATA/index/freeworld out, delete the whole yacy, git clone then move it back in?

**Comment by songproducer** [comment]
@luccioman I've exported the index as a json file, created the folder DATA/SURROGATES/in   and moved the json file here, but it's not importing.

**Comment by songproducer** [comment]
@luccioman I also tried changing directory into DATA/SURROGATES/in and running:
curl -XPOST localhost:9200/collection1/yacy/_bulk --data-binary @yacy_dump_f200001010800_l353108120800_n201808062002_c000002810403_tc.flatjson

but I got 
curl: (7) Failed to connect to localhost port 9200: Connection refused

I also tried changing the port to 8090 but then got:
```

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /collection1/yacy/_bulk. Reason:
<pre>    Not Found</pre></p><br/><hr /><small>YaCy 1.921  - <i> powered by Jetty </i> - </small><br/>      
```

**Comment by luccioman** [comment]
@songproducer please open a new issue when asking for different things rather than commenting a closed issue as these comments are likely to be missed.
By the way, when upgrading your YaCy version (with `git pull` for example if you are running directly YaCy from the sources), you can safely keep your whole DATA directory rather than using index export/import operations.
