### ISSUE TITLE
Solr 7.4.0

### ISSUE THREAD

**Issue by yacylover** [yacy/yacy_search_server#212]
Hi,

I just managed to adapt/transform the YaCy Config & Schema to Solr 7.4.0. The key to success is an artifact named  <luceneMatchVersion>6.5.0</luceneMatchVersion>. When I'm trying to mount this external Solr Instance at page 'IndexFederated_p.html' it fails. The Log shows

`
W 2018/08/06 18:55:54 net.yacy.cora.federate.solr.connector.SolrServerConnector Error from server at http://127.0.0.1:8984/solr/collection1: unknown handler: null java.io.IOException: Error from server at http://127.0.0.1:8984/solr/collection1: unknown handler: null at net.yacy.cora.federate.solr.connector.RemoteSolrConnector.getResponseByParams(RemoteSolrConnector.java:116) at net.yacy.cora.federate.solr.connector.SolrServerConnector.getSizeQueryRequest(SolrServerConnector.java:387) at net.yacy.cora.federate.solr.connector.SolrServerConnector.getSize(SolrServerConnector.java:369) at IndexFederated_p.respond(IndexFederated_p.java:191) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at net.yacy.http.servlets.YaCyDefaultServlet.invokeServlet(YaCyDefaultServlet.java:673) at net.yacy.http.servlets.YaCyDefaultServlet.handleTemplate(YaCyDefaultServlet.java:884) at net.yacy.http.servlets.YaCyDefaultServlet.doGet(YaCyDefaultServlet.java:315) at net.yacy.http.servlets.YaCyDefaultServlet.doPost(YaCyDefaultServlet.java:377) at javax.servlet.http.HttpServlet.service(HttpServlet.java:707) at javax.servlet.http.HttpServlet.service(HttpServlet.java:790) at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:864) at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:535) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:146) at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:666) at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:513) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257) at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1595) at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255) at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203) at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473) at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1564) at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201) at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155) at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144) at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:219) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at net.yacy.http.CrashProtectionHandler.handle(CrashProtectionHandler.java:33) at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132) at org.eclipse.jetty.server.Server.handle(Server.java:531) at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:352) at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:260) at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:281) at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:102) at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:319) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:175) at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:133) at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366) at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754) at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672) at java.lang.Thread.run(Thread.java:748)

I 2018/08/06 18:55:54 RemoteSolrConnector connecting Solr with url : http://127.0.0.1:8984/solr/collection1
`

Can someone help me please?

Greetiings from germany

LA_FORGE

**Comment by yacylover** [comment]
JSON is now the default response format. If you rely on XML responses, you must now define wt=xml in your request. In addition, line indentation is enabled by default (indent=on).

Found this at the release notes of solr 7.4.0. Is this the cause of the error I'm getting? If so, is it possible to fix this with little effort? Or is it complex? My java skills are at the early beginner level :-(

**Comment by luccioman** [comment]
Hi @yacylover , beyond the Solr configuration and schema files, did you also upgrade Lucene and Solr dependencies (jar files lib/lucene-*.jar and lib/solr-*.jar)?

**Comment by yacylover** [comment]
Hi,

no I didn't upgrade the dependencies because my java skills are at the
early beginning stage :-( I only followed the tutorial in our wiki

http://www.yacy-websearch.net/wiki/index.php/Dev:Solr

when I'm trying to mount an external Solr Instance at the page
http://localhost:8090/IndexFederated_p.html

It doesn't work anymore :-( I also "downgraded" my external Solr to version 6.6.2 (This seems to be the current version in YaCy's /lib/  directory. But the results are the same as in the log above.

Can someone in our community please update our wiki article at the URL
mentioned above on how to connect an external Solr instance?

Greetings from germany

LA_FORGE

**Comment by luccioman** [comment]
@yacylover , the most recent documentation describing steps for attaching an external Solr server to YaCy is in the [yacy.init](https://github.com/yacy/yacy_search_server/blob/21ad9435ec6bccaea87e91f4d6111d47b4458a26/defaults/yacy.init#L1289) file.

But this is true that it is not very detailed, and updating the wiki would certainly help.

**Comment by yacylover** [comment]
Thank you very much. This worked very well. I'll update our wiki during the week.
