### ISSUE TITLE
Invalid date string - yacy becomes unresponsive

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#230]
Happens when I leave Yacy running overnight.

```
W 2018/09/19 03:12:20 ConcurrentLog org.apache.solr.common.SolrException: Invalid Date String:'Sat Dec 31 08:00:00 AWST 2016'
org.apache.solr.common.SolrException: Invalid Date String:'Sat Dec 31 08:00:00 AWST 2016'
	at org.apache.solr.util.DateMathParser.parseMath(DateMathParser.java:234)
	at org.apache.solr.schema.TrieField.createField(TrieField.java:644)
	at org.apache.solr.schema.TrieField.createFields(TrieField.java:659)
	at org.apache.solr.update.DocumentBuilder.addField(DocumentBuilder.java:72)
	at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:179)
	at org.apache.solr.update.AddUpdateCommand.getLuceneDocument(AddUpdateCommand.java:102)
	at org.apache.solr.update.DirectUpdateHandler2.updateDocument(DirectUpdateHandler2.java:922)
	at org.apache.solr.update.DirectUpdateHandler2.updateDocOrDocValues(DirectUpdateHandler2.java:913)
	at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:302)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:239)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:194)
	at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:67)
	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:979)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:1192)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:748)
	at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:103)
	at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:261)
	at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:188)
	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:68)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2477)
	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:179)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:160)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:173)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:190)
	at net.yacy.cora.federate.solr.connector.SolrServerConnector.add(SolrServerConnector.java:213)
	at net.yacy.cora.federate.solr.connector.MirrorSolrConnector.add(MirrorSolrConnector.java:204)
	at net.yacy.search.index.Fulltext.putDocument(Fulltext.java:377)
	at net.yacy.search.index.Segment.putDocument(Segment.java:556)
	at net.yacy.search.Switchboard.processSurrogate(Switchboard.java:2235)
	at net.yacy.search.Switchboard.surrogateProcess(Switchboard.java:2442)
	at net.yacy.search.Switchboard$12.jobImpl(Switchboard.java:1156)
	at net.yacy.kelondro.workflow.InstantBusyThread.job(InstantBusyThread.java:64)
	at net.yacy.kelondro.workflow.AbstractBusyThread.run(AbstractBusyThread.java:215)
```

**Comment by luccioman** [comment]
Hi @songproducer don't you have other errors reported in your logs? This one is a warning (prefixed with 'W'), and chances are that it is not this one that makes YaCy unresponsive...
Are you running large crawls? With which YaCy exact version?

**Comment by songproducer** [comment]
Hi @luccioman I saw heaps of warnings like this but I couldn't see any other errors at the time. I'll close this issue for now as it hasn't happened again recently.

**Comment by songproducer** [comment]
Saw this error today after a restart.

> E 2018/09/24 00:41:01 org.apache.solr.handler.RequestHandlerBase org.apache.solr.common.SolrException: Invalid Date String:'Fri Mar 13 22:56:23 AWDT 2009'
> 	at org.apache.solr.util.DateMathParser.parseMath(DateMathParser.java:234)
> 	at org.apache.solr.schema.TrieField.createField(TrieField.java:644)
> 	at org.apache.solr.schema.TrieField.createFields(TrieField.java:659)
> 	at org.apache.solr.update.DocumentBuilder.addField(DocumentBuilder.java:72)
> 	at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:179)
> 	at org.apache.solr.update.AddUpdateCommand.getLuceneDocument(AddUpdateCommand.java:102)
> 	at org.apache.solr.update.DirectUpdateHandler2.updateDocument(DirectUpdateHandler2.java:922)
> 	at org.apache.solr.update.DirectUpdateHandler2.updateDocOrDocValues(DirectUpdateHandler2.java:913)
> 	at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:302)
> 	at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:239)
> 	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:194)
> 	at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:67)
> 	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
> 	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:979)
> 	at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:1192)
> 	at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:748)
> 	at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:103)
> 	at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:261)
> 	at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:188)
> 	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
> 	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:68)
> 	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
> 	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2477)
> 	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:179)
> 	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:160)
> 	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:173)
> 	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:190)
> 	at net.yacy.cora.federate.solr.connector.SolrServerConnector.add(SolrServerConnector.java:237)
> 	at net.yacy.cora.federate.solr.connector.MirrorSolrConnector.add(MirrorSolrConnector.java:204)
> 	at net.yacy.search.index.Fulltext.putDocument(Fulltext.java:377)
> 	at net.yacy.search.index.Segment.putDocument(Segment.java:556)
> 	at net.yacy.search.Switchboard.processSurrogate(Switchboard.java:2235)
> 	at net.yacy.search.Switchboard.surrogateProcess(Switchboard.java:2442)
> 	at net.yacy.search.Switchboard$12.jobImpl(Switchboard.java:1156)
> 	at net.yacy.kelondro.workflow.InstantBusyThread.job(InstantBusyThread.java:64)
> 	at net.yacy.kelondro.workflow.AbstractBusyThread.run(AbstractBusyThread.java:215)
