### ISSUE TITLE
Error while postprocessing index

### ISSUE THREAD

**Issue by Marx1st** [yacy/yacy_search_server#285]
When "process_sxt" is active I get the following error for a lot of documents in the index:

`W 2019/02/22 10:40:40 ConcurrentLog java.io.IOException: org.apache.solr.common.SolrException: Exception writing document id EkU_SLSdFRCC to the index; possible analysis error: DocValuesField "coordinate_p_0_coordinate" appears more than once in this document (only one value is allowed per field)
java.io.IOException: org.apache.solr.common.SolrException: Exception writing document id EkU_SLSdFRCC to the index; possible analysis error: DocValuesField "coordinate_p_0_coordinate" appears more than once in this document (only one value is allowed per field)
	at net.yacy.cora.federate.solr.connector.SolrServerConnector.add(SolrServerConnector.java:240)
	at net.yacy.cora.federate.solr.connector.MirrorSolrConnector.add(MirrorSolrConnector.java:204)
	at net.yacy.cora.federate.solr.connector.AbstractSolrConnector.update(AbstractSolrConnector.java:600)
	at net.yacy.search.schema.CollectionConfiguration$1.run(CollectionConfiguration.java:1470)
Caused by: org.apache.solr.common.SolrException: Exception writing document id EkU_SLSdFRCC to the index; possible analysis error: DocValuesField "coordinate_p_0_coordinate" appears more than once in this document (only one value is allowed per field)
	at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:199)
	at org.apache.solr.update.processor.RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:67)
	at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:979)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:1192)
	at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:748)
	at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:103)
	at org.apache.solr.handler.loader.XMLLoader.processUpdate(XMLLoader.java:261)
	at org.apache.solr.handler.loader.XMLLoader.load(XMLLoader.java:188)
	at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:68)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:173)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2477)
	at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:179)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:160)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:173)
	at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:190)
	at net.yacy.cora.federate.solr.connector.SolrServerConnector.add(SolrServerConnector.java:237)`

**Comment by luccioman** [comment]
Hi @Marx1st could you detail a document sample URL? You can for example retrieve the one that generated this error trace by requesting `/solr/select?q=id:EkU_SLSdFRCC&fl=sku` on your peer.

**Comment by Marx1st** [comment]
Hi! I did this for a different URL with the same error. See attached .xml file.
[select.xml.zip](https://github.com/yacy/yacy_search_server/files/3248226/select.xml.zip)
