### ISSUE TITLE
Your peer cannot be reached from outside

### ISSUE THREAD

**Issue by slrslr** [yacy/yacy_search_server#287]
On Windows 10 computer at http://localhost:8090/ConfigBasic.html
i see "Your peer cannot be reached from outside"
YaCy version: 1.92/9000
I am using OpenVPN client app in MS Windows and the server is located in different country. It is Linux Ubuntu with iptables firewall. I want to ask how do i open the port on the VPN server and forward it.
I already setup [virtual server forwarding on my home router that i believe should work](https://snag.gy/NbMHQU.jpg).

**Comment by smokingwheels** [comment]
Try.
sudo ufw allow 8090

**Comment by slrslr** [comment]
> # sudo ufw allow 8090
> sudo: ufw: command not found

I think my port is not blocked as my VPN server firewall default policy is ACCEPT:

> \# iptables -L
> Chain INPUT (policy ACCEPT)
> target     prot opt source               destination
> 
> Chain FORWARD (policy ACCEPT)
> target     prot opt source               destination
> 
> Chain OUTPUT (policy ACCEPT)
> target     prot opt source               destination

But on my client computer i found no firewall rule for Yacy, like it never made a connection attempt. My FW usually asks when new app try to connect internet. In FW config. i found yacycore.jar running, unsure if needed to grant IN/OUT traffic permission. I tried. Also tried to allow port 8090 in my web browser firewall ruleset, no luck.

Unsure if Yacy is using Java, i have C:\Program Files (x86)\Java\jre1.8.0_111\bin\javaw.exe set as Blocked application for internet traffic. java.exe is allowed. I do not know what is appropriate safe setting for java on Windows?

**Comment by frankenstein91** [comment]
Where does your Yacy Peer run on the Windows PC or on the Linux server?

**Comment by slrslr** [comment]
Yacy software is running on the Windows, but since i am using the VPN server, i think it is up to server (Linux OS) to make sure it forward incoming requests to my Windows client.

**Comment by yuenshui** [comment]
`Ops!

Message: /home/data/software/yacy/htroot/ConfigBasic.html
javax.servlet.ServletException: /home/data/software/yacy/htroot/ConfigBasic.html
        at net.yacy.http.servlets.YaCyDefaultServlet.handleTemplate(YaCyDefaultServlet.java:896)
        at net.yacy.http.servlets.YaCyDefaultServlet.doGet(YaCyDefaultServlet.java:302)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:791)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
        at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:766)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
        at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at net.yacy.http.CrashProtectionHandler.handle(CrashProtectionHandler.java:33)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
        at org.eclipse.jetty.server.Server.handle(Server.java:516)
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
        at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
        at java.lang.Thread.run(Thread.java:748)
`
`yum search java|grep -i --color JDKyum install java-1.8.0-openjdk  java-1.8.0-openjdk-devel


export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.292.b10-0.el8_3.x86_64
export JRE_HOME=/usr/lib/jvm/jre-1.8.0-openjdk-1.8.0.292.b10-0.el8_3.x86_64
export CLASSPATH=.:$JAVA_HOME/jre/lib:$JAVA_HOME/lib
export PATH=$PATH:$JAVA_HOME/bin


# tar xfz yacy_v1.924_20210209_10069.tar.gz
# cd yacy/
# chmod +x startYACY.sh
# ./startYACY.sh


****************** YaCy Web Crawler/Indexer & Search Engine *******************
**** (C) by Michael Peter Christen, usage granted under the GPL Version 2  ****
****   USE AT YOUR OWN RISK! Project home and releases: http://yacy.net/   ****
**  LOG of       YaCy: DATA/LOG/yacy00.log (and yacy<xx>.log)                **
**  STOP         YaCy: execute stopYACY.sh and wait some seconds             **
**  GET HELP for YaCy: join our community at https://searchlab.eu            **
*******************************************************************************
>> YaCy started as daemon process. Administration at http://localhost:8090 <<
`

**Comment by debian-user-france1** [comment]
That's something else and can be fixed by configuring a password instead of only allowing localhost to access the admin panel @yuenshui

**Comment by smokingwheels** [comment]
try bin/passwd.sh <password>
