### ISSUE TITLE
Shutdown doesn't complete

### ISSUE THREAD

**Issue by songproducer** [yacy/yacy_search_server#385]
```
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:786)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:743)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at status_p.respond(status_p.java:100)
	... 42 more

```

**Comment by songproducer** [comment]
After killing I ran the stop command:

```
tail: cannot open 'DATA/LOG/yacy00.log and fuser' for reading: No such file or directory
==> DATA/LOG/yacy00.log <==
I 2020/11/10 01:01:37 HeapReader close HeapFile api.bheap; trace: net.yacy.kelondro.blob.HeapModifier.close(HeapModifier.java:82) -> net.yacy.kelondro.blob.Heap.close(Heap.java:305) -> net.yacy.kelondro.blob.Heap.close(Heap.java:311) -> net.yacy.kelondro.blob.BEncodedHeap.close(BEncodedHeap.java:532) -> net.yacy.kelondro.blob.Tables.close(Tables.java:274) -> net.yacy.search.Switchboard.close(Switchboard.java:2022) -> net.yacy.yacy.startup(yacy.java:409) -> net.yacy.yacy.main(yacy.java:865)
I 2020/11/10 01:01:37 Heap closing heap /mnt/2c094727-1118-4a5b-ab85-2169901da8e9/yacy_search_server/DATA/WORK/robots.bheap
I 2020/11/10 01:01:37 HeapReader wrote a dump for the 0 gap entries of robots.bheap in 0 milliseconds.
I 2020/11/10 01:01:37 HeapReader wrote a dump for the 1142 index entries of robots.bheap in 4 milliseconds.
I 2020/11/10 01:01:37 HeapReader close HeapFile robots.bheap; trace: net.yacy.kelondro.blob.HeapModifier.close(HeapModifier.java:82) -> net.yacy.kelondro.blob.Heap.close(Heap.java:305) -> net.yacy.kelondro.blob.Heap.close(Heap.java:311) -> net.yacy.kelondro.blob.BEncodedHeap.close(BEncodedHeap.java:532) -> net.yacy.kelondro.blob.Tables.close(Tables.java:274) -> net.yacy.search.Switchboard.close(Switchboard.java:2022) -> net.yacy.yacy.startup(yacy.java:409) -> net.yacy.yacy.main(yacy.java:865)
I 2020/11/10 01:01:37 HostQueue opened HostQueue /mnt/2c094727-1118-4a5b-ab85-2169901da8e9/yacy_search_server/DATA/INDEX/freeworld/QUEUES/CrawlerLimitStacks/www.xinsu360.com-#wuj5FY.80 with 2 urls.
I 2020/11/10 01:01:37 HostQueue opened HostQueue /mnt/2c094727-1118-4a5b-ab85-2169901da8e9/yacy_search_server/DATA/INDEX/freeworld/QUEUES/CrawlerLimitStacks/csrracingtools.webblogg.se-#t4RWXA.80 with 1 urls.
I 2020/11/10 01:01:37 ConcurrentLog shutdown of ConcurrentLog.Worker: injection of poison message
I 2020/11/10 01:01:37 ConcurrentLog terminating ConcurrentLog.Worker with 0 cached loglines.
I 2020/11/10 01:01:37 ConcurrentLog shutdown of ConcurrentLog.Worker: terminated
```

**Comment by Orbiter** [comment]
Made a fix for the NPE
