### ISSUE TITLE
net.yacy.cora.util.Html2ImageTest > testPdf2image FAILED

### ISSUE THREAD

**Issue by sebastianmbobrecki** [yacy/yacy_search_server#454]
With current tree when I try to build with `./gradlew build` on OpenJDK 17.0.1.u12 I get an error:
```
> Task :test

net.yacy.cora.util.Html2ImageTest > testPdf2image FAILED
    java.lang.AssertionError at Html2ImageTest.java:62

195 tests completed, 1 failed

> Task :test FAILED

FAILURE: Build failed with an exception.
```
Report from failing test:
```
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at net.yacy.cora.util.Html2ImageTest.testPdf2image(Html2ImageTest.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy1/jdk.proxy1.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:176)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:133)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by reger24** [comment]
can't reproduce / confirm issue,
..tested with OpenJDK v17.0.2 (Debian) and  jdk-17.0.2 (Windows)
in both cases all test succeed w/o failure

**Comment by sebastianmbobrecki** [comment]
Now, same system as before, after `git pull` error has changed :
```
$ ./gradlew build
Starting a Gradle Daemon (subsequent builds will be faster)

> Configure project :
[ant:javac] warning: [options] bootstrap class path not set in conjunction with -source 8
[ant:javac] /home/sebastian/yacy_git/yacy_search_server/htroot/Blacklist_p.java:399: error: cannot find symbol
[ant:javac]             String[] sortedlist = BlacklistHelper.blacklistToSortedArray(blacklistToUse);
[ant:javac]                                                  ^
[ant:javac]   symbol:   method blacklistToSortedArray(String)
[ant:javac]   location: class BlacklistHelper
[ant:javac] 1 error
[ant:javac] 1 warning

FAILURE: Build failed with an exception.

* Where:
Build file '/home/sebastian/yacy_git/yacy_search_server/build.gradle' line: 197

* What went wrong:
A problem occurred evaluating root project 'yacycore'.
> Compile failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.3.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 12s
```

**Comment by reger24** [comment]
that's a different topic - but know reason

Quickfix:  delete your  build directory once  (after that build worked for me)

**Comment by sebastianmbobrecki** [comment]
Thanks, after fresh clone it's working with only minor warnings:
```
$ ./gradlew build

> Task :compileJava
/home/sebastian/yacy_git/yacy_search_server/source/net/yacy/visualization/DemoApplet.java:3: warning: [removal] Applet in java.applet has been deprecated and marked for removal
import java.applet.Applet;
                  ^
/home/sebastian/yacy_git/yacy_search_server/source/net/yacy/cora/protocol/ftp/FTPClient.java:2523: warning: [removal] AccessControlException in java.security has been deprecated and marked for removal
        } catch (final java.security.AccessControlException e) {
                                    ^
/home/sebastian/yacy_git/yacy_search_server/source/net/yacy/cora/protocol/ftp/FTPClient.java:2539: warning: [removal] AccessControlException in java.security has been deprecated and marked for removal
        } catch (final java.security.AccessControlException e) {
                                    ^
/home/sebastian/yacy_git/yacy_search_server/source/net/yacy/cora/protocol/ftp/FTPClient.java:2785: warning: [removal] AccessControlException in java.security has been deprecated and marked for removal
        } catch (final java.security.AccessControlException e) {
                                    ^
/home/sebastian/yacy_git/yacy_search_server/source/net/yacy/visualization/DemoApplet.java:9: warning: [removal] Applet in java.applet has been deprecated and marked for removal
public class DemoApplet extends Applet implements Runnable {
                                ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 warnings
```
```
./gradlew packageDist

> Configure project :
[ant:javac] warning: [options] bootstrap class path not set in conjunction with -source 8
[ant:javac] 1 warning

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.
```

**Comment by reger24** [comment]
good to here, as it seems working - additonally see also commit https://github.com/yacy/yacy_search_server/commit/3867741a4156d77b81beb4f574da9e3ea6e44fcd
