### ISSUE TITLE
Error: TransactionLog doesn't know how to serialize class

### ISSUE THREAD

**Issue by Scre13** [yacy/yacy_search_server#496]
When postprocessing is active, the following error is logged very frequently:

```
E 2022/08/25 16:26:58 org.apache.solr.handler.RequestHandlerBase org.apache.solr.common.SolrException: TransactionLog doesn't know how to serialize class org.apache.lucene.document.LazyDocument$LazyField; try implementing ObjectResolver?
        at org.apache.solr.update.TransactionLog$1.resolve(TransactionLog.java:100)
        at org.apache.solr.common.util.JavaBinCodec.writeVal(JavaBinCodec.java:266)
        at org.apache.solr.common.util.JavaBinCodec$BinEntryWriter.put(JavaBinCodec.java:441)
        at org.apache.solr.common.ConditionalKeyMapWriter$EntryWriterWrapper.put(ConditionalKeyMapWriter.java:44)
        at org.apache.solr.common.MapWriter$EntryWriter.putNoEx(MapWriter.java:101)
        at org.apache.solr.common.MapWriter$EntryWriter.lambda$getBiConsumer$0(MapWriter.java:161)
        at org.apache.solr.common.SolrInputDocument.lambda$writeMap$0(SolrInputDocument.java:59)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.apache.solr.common.SolrInputDocument.writeMap(SolrInputDocument.java:61)
        at org.apache.solr.common.util.JavaBinCodec.writeSolrInputDocument(JavaBinCodec.java:667)
        at org.apache.solr.update.TransactionLog.write(TransactionLog.java:397)
        at org.apache.solr.update.UpdateLog.add(UpdateLog.java:585)
        at org.apache.solr.update.UpdateLog.add(UpdateLog.java:557)
        at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:351)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:294)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:241)
        at org.apache.solr.update.processor.RunUpdateProcessorFactory$RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:73)
        at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:256)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doVersionAdd(DistributedUpdateProcessor.java:495)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.lambda$versionAdd$0(DistributedUpdateProcessor.java:336)
        at org.apache.solr.update.VersionBucket.runWithLock(VersionBucket.java:50)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:336)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:222)
        at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:106)
        at org.apache.solr.handler.loader.JavabinLoader$1.update(JavabinLoader.java:110)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readOuterMostDocIterator(JavaBinUpdateRequestCodec.java:343)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readIterator(JavaBinUpdateRequestCodec.java:291)
        at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:338)
        at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:283)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readNamedList(JavaBinUpdateRequestCodec.java:244)
        at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:303)
        at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:283)
        at org.apache.solr.common.util.JavaBinCodec.unmarshal(JavaBinCodec.java:196)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec.unmarshal(JavaBinUpdateRequestCodec.java:131)
        at org.apache.solr.handler.loader.JavabinLoader.parseAndLoadDocs(JavabinLoader.java:122)
        at org.apache.solr.handler.loader.JavabinLoader.load(JavabinLoader.java:70)
        at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:82)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:216)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2646)
        at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:229)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:214)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:177)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:194)
        at net.yacy.cora.federate.solr.connector.SolrServerConnector.add(SolrServerConnector.java:213)
        at net.yacy.cora.federate.solr.connector.MirrorSolrConnector.add(MirrorSolrConnector.java:204)
        at net.yacy.cora.federate.solr.connector.AbstractSolrConnector.update(AbstractSolrConnector.java:606)
        at net.yacy.search.schema.CollectionConfiguration$1.run(CollectionConfiguration.java:1469)

W 2022/08/25 16:26:58 ConcurrentLog * org.apache.solr.common.SolrException: TransactionLog doesn't know how to serialize class org.apache.lucene.document.LazyDocument$LazyField; try implementing ObjectResolver?
org.apache.solr.common.SolrException: TransactionLog doesn't know how to serialize class org.apache.lucene.document.LazyDocument$LazyField; try implementing ObjectResolver?
        at org.apache.solr.update.TransactionLog$1.resolve(TransactionLog.java:100)
        at org.apache.solr.common.util.JavaBinCodec.writeVal(JavaBinCodec.java:266)
        at org.apache.solr.common.util.JavaBinCodec$BinEntryWriter.put(JavaBinCodec.java:441)
        at org.apache.solr.common.ConditionalKeyMapWriter$EntryWriterWrapper.put(ConditionalKeyMapWriter.java:44)
        at org.apache.solr.common.MapWriter$EntryWriter.putNoEx(MapWriter.java:101)
        at org.apache.solr.common.MapWriter$EntryWriter.lambda$getBiConsumer$0(MapWriter.java:161)
        at org.apache.solr.common.SolrInputDocument.lambda$writeMap$0(SolrInputDocument.java:59)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.apache.solr.common.SolrInputDocument.writeMap(SolrInputDocument.java:61)
        at org.apache.solr.common.util.JavaBinCodec.writeSolrInputDocument(JavaBinCodec.java:667)
        at org.apache.solr.update.TransactionLog.write(TransactionLog.java:397)
        at org.apache.solr.update.UpdateLog.add(UpdateLog.java:585)
        at org.apache.solr.update.UpdateLog.add(UpdateLog.java:557)
        at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:351)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:294)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:241)
        at org.apache.solr.update.processor.RunUpdateProcessorFactory$RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:73)
        at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:256)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doVersionAdd(DistributedUpdateProcessor.java:495)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.lambda$versionAdd$0(DistributedUpdateProcessor.java:336)
        at org.apache.solr.update.VersionBucket.runWithLock(VersionBucket.java:50)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:336)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:222)
        at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:106)
        at org.apache.solr.handler.loader.JavabinLoader$1.update(JavabinLoader.java:110)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readOuterMostDocIterator(JavaBinUpdateRequestCodec.java:343)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readIterator(JavaBinUpdateRequestCodec.java:291)
        at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:338)
        at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:283)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readNamedList(JavaBinUpdateRequestCodec.java:244)
        at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:303)
        at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:283)
        at org.apache.solr.common.util.JavaBinCodec.unmarshal(JavaBinCodec.java:196)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec.unmarshal(JavaBinUpdateRequestCodec.java:131)
        at org.apache.solr.handler.loader.JavabinLoader.parseAndLoadDocs(JavabinLoader.java:122)
        at org.apache.solr.handler.loader.JavabinLoader.load(JavabinLoader.java:70)
        at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:82)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:216)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2646)
        at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:229)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:214)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:177)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:194)
        at net.yacy.cora.federate.solr.connector.SolrServerConnector.add(SolrServerConnector.java:213)
        at net.yacy.cora.federate.solr.connector.MirrorSolrConnector.add(MirrorSolrConnector.java:204)
        at net.yacy.cora.federate.solr.connector.AbstractSolrConnector.update(AbstractSolrConnector.java:606)
        at net.yacy.search.schema.CollectionConfiguration$1.run(CollectionConfiguration.java:1469)
I 2022/08/25 16:26:58 org.apache.solr.update.processor.LogUpdateProcessorFactory [collection1]  webapp=null path=/update params={}{} 0 2
E 2022/08/25 16:26:58 org.apache.solr.handler.RequestHandlerBase org.apache.solr.common.SolrException: TransactionLog doesn't know how to serialize class org.apache.lucene.document.LazyDocument$LazyField; try implementing ObjectResolver?
        at org.apache.solr.update.TransactionLog$1.resolve(TransactionLog.java:100)
        at org.apache.solr.common.util.JavaBinCodec.writeVal(JavaBinCodec.java:266)
        at org.apache.solr.common.util.JavaBinCodec$BinEntryWriter.put(JavaBinCodec.java:441)
        at org.apache.solr.common.ConditionalKeyMapWriter$EntryWriterWrapper.put(ConditionalKeyMapWriter.java:44)
        at org.apache.solr.common.MapWriter$EntryWriter.putNoEx(MapWriter.java:101)
        at org.apache.solr.common.MapWriter$EntryWriter.lambda$getBiConsumer$0(MapWriter.java:161)
        at org.apache.solr.common.SolrInputDocument.lambda$writeMap$0(SolrInputDocument.java:59)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.apache.solr.common.SolrInputDocument.writeMap(SolrInputDocument.java:61)
        at org.apache.solr.common.util.JavaBinCodec.writeSolrInputDocument(JavaBinCodec.java:667)
        at org.apache.solr.update.TransactionLog.write(TransactionLog.java:397)
        at org.apache.solr.update.UpdateLog.add(UpdateLog.java:585)
        at org.apache.solr.update.UpdateLog.add(UpdateLog.java:557)
        at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:351)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:294)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:241)
        at org.apache.solr.update.processor.RunUpdateProcessorFactory$RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:73)
        at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:256)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doVersionAdd(DistributedUpdateProcessor.java:495)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.lambda$versionAdd$0(DistributedUpdateProcessor.java:336)
        at org.apache.solr.update.VersionBucket.runWithLock(VersionBucket.java:50)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:336)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:222)
        at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:106)
        at org.apache.solr.handler.loader.JavabinLoader$1.update(JavabinLoader.java:110)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readOuterMostDocIterator(JavaBinUpdateRequestCodec.java:343)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readIterator(JavaBinUpdateRequestCodec.java:291)
        at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:338)
        at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:283)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readNamedList(JavaBinUpdateRequestCodec.java:244)
        at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:303)
        at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:283)
        at org.apache.solr.common.util.JavaBinCodec.unmarshal(JavaBinCodec.java:196)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec.unmarshal(JavaBinUpdateRequestCodec.java:131)
        at org.apache.solr.handler.loader.JavabinLoader.parseAndLoadDocs(JavabinLoader.java:122)
        at org.apache.solr.handler.loader.JavabinLoader.load(JavabinLoader.java:70)
        at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:82)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:216)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2646)
        at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:229)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:214)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:177)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:194)
        at net.yacy.cora.federate.solr.connector.SolrServerConnector.add(SolrServerConnector.java:227)
        at net.yacy.cora.federate.solr.connector.MirrorSolrConnector.add(MirrorSolrConnector.java:204)
        at net.yacy.cora.federate.solr.connector.AbstractSolrConnector.update(AbstractSolrConnector.java:606)
        at net.yacy.search.schema.CollectionConfiguration$1.run(CollectionConfiguration.java:1469)

W 2022/08/25 16:26:58 ConcurrentLog * org.apache.solr.common.SolrException: TransactionLog doesn't know how to serialize class org.apache.lucene.document.LazyDocument$LazyField; try implementing ObjectResolver?
org.apache.solr.common.SolrException: TransactionLog doesn't know how to serialize class org.apache.lucene.document.LazyDocument$LazyField; try implementing ObjectResolver?
        at org.apache.solr.update.TransactionLog$1.resolve(TransactionLog.java:100)
        at org.apache.solr.common.util.JavaBinCodec.writeVal(JavaBinCodec.java:266)
        at org.apache.solr.common.util.JavaBinCodec$BinEntryWriter.put(JavaBinCodec.java:441)
        at org.apache.solr.common.ConditionalKeyMapWriter$EntryWriterWrapper.put(ConditionalKeyMapWriter.java:44)
        at org.apache.solr.common.MapWriter$EntryWriter.putNoEx(MapWriter.java:101)
        at org.apache.solr.common.MapWriter$EntryWriter.lambda$getBiConsumer$0(MapWriter.java:161)
        at org.apache.solr.common.SolrInputDocument.lambda$writeMap$0(SolrInputDocument.java:59)
        at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
        at org.apache.solr.common.SolrInputDocument.writeMap(SolrInputDocument.java:61)
        at org.apache.solr.common.util.JavaBinCodec.writeSolrInputDocument(JavaBinCodec.java:667)
        at org.apache.solr.update.TransactionLog.write(TransactionLog.java:397)
        at org.apache.solr.update.UpdateLog.add(UpdateLog.java:585)
        at org.apache.solr.update.UpdateLog.add(UpdateLog.java:557)
        at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:351)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:294)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:241)
        at org.apache.solr.update.processor.RunUpdateProcessorFactory$RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:73)
        at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:256)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doVersionAdd(DistributedUpdateProcessor.java:495)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.lambda$versionAdd$0(DistributedUpdateProcessor.java:336)
        at org.apache.solr.update.VersionBucket.runWithLock(VersionBucket.java:50)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:336)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:222)
        at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:106)
        at org.apache.solr.handler.loader.JavabinLoader$1.update(JavabinLoader.java:110)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readOuterMostDocIterator(JavaBinUpdateRequestCodec.java:343)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readIterator(JavaBinUpdateRequestCodec.java:291)
        at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:338)
        at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:283)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readNamedList(JavaBinUpdateRequestCodec.java:244)
        at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:303)
        at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:283)
        at org.apache.solr.common.util.JavaBinCodec.unmarshal(JavaBinCodec.java:196)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec.unmarshal(JavaBinUpdateRequestCodec.java:131)
        at org.apache.solr.handler.loader.JavabinLoader.parseAndLoadDocs(JavabinLoader.java:122)
        at org.apache.solr.handler.loader.JavabinLoader.load(JavabinLoader.java:70)
        at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:82)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:216)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2646)
        at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:229)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:214)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:177)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:194)
        at net.yacy.cora.federate.solr.connector.SolrServerConnector.add(SolrServerConnector.java:227)
        at net.yacy.cora.federate.solr.connector.MirrorSolrConnector.add(MirrorSolrConnector.java:204)
        at net.yacy.cora.federate.solr.connector.AbstractSolrConnector.update(AbstractSolrConnector.java:606)
        at net.yacy.search.schema.CollectionConfiguration$1.run(CollectionConfiguration.java:1469)
```

YaCy version: 1.925/9749
Java version: 11.0.16

**Comment by Scre13** [comment]
I have to disappoint you 😒

YaCy version: yacy_v1.926_202210051710_a0ddc168e
Java version: 11.0.16

The failure above has gone, but now a similar error to LogUpdateProcessorFactory appears:


```
I 2022/10/05 19:07:33 org.apache.solr.update.processor.LogUpdateProcessorFactory [collection1]  webapp=null path=/update params={}{} 0 0
W 2022/10/05 19:07:33 ConcurrentLog * java.lang.NoClassDefFoundError: com/google/common/util/concurrent/internal/InternalFutureFailureAccess
java.lang.NoClassDefFoundError: com/google/common/util/concurrent/internal/InternalFutureFailureAccess
        at com.google.common.cache.LocalCache$LoadingValueReference.<init>(LocalCache.java:3476)
        at com.google.common.cache.LocalCache$LoadingValueReference.<init>(LocalCache.java:3480)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2138)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
        at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4863)
        at org.apache.solr.schema.AbstractSpatialFieldType.getStrategy(AbstractSpatialFieldType.java:430)
        at org.apache.solr.schema.AbstractSpatialFieldType.createFields(AbstractSpatialFieldType.java:236)
        at org.apache.solr.update.DocumentBuilder.addField(DocumentBuilder.java:65)
        at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:179)
        at org.apache.solr.update.AddUpdateCommand.makeLuceneDocs(AddUpdateCommand.java:243)
        at org.apache.solr.update.DirectUpdateHandler2.updateDocOrDocValues(DirectUpdateHandler2.java:962)
        at org.apache.solr.update.DirectUpdateHandler2.doNormalUpdate(DirectUpdateHandler2.java:342)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc0(DirectUpdateHandler2.java:294)
        at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:241)
        at org.apache.solr.update.processor.RunUpdateProcessorFactory$RunUpdateProcessor.processAdd(RunUpdateProcessorFactory.java:73)
        at org.apache.solr.update.processor.UpdateRequestProcessor.processAdd(UpdateRequestProcessor.java:55)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doLocalAdd(DistributedUpdateProcessor.java:263)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.doVersionAdd(DistributedUpdateProcessor.java:502)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.lambda$versionAdd$0(DistributedUpdateProcessor.java:343)
        at org.apache.solr.update.VersionBucket.runWithLock(VersionBucket.java:50)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.versionAdd(DistributedUpdateProcessor.java:343)
        at org.apache.solr.update.processor.DistributedUpdateProcessor.processAdd(DistributedUpdateProcessor.java:229)
        at org.apache.solr.update.processor.LogUpdateProcessorFactory$LogUpdateProcessor.processAdd(LogUpdateProcessorFactory.java:106)
        at org.apache.solr.handler.loader.JavabinLoader$1.update(JavabinLoader.java:110)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readOuterMostDocIterator(JavaBinUpdateRequestCodec.java:343)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readIterator(JavaBinUpdateRequestCodec.java:291)
        at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:338)
        at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:283)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec$StreamingCodec.readNamedList(JavaBinUpdateRequestCodec.java:244)
        at org.apache.solr.common.util.JavaBinCodec.readObject(JavaBinCodec.java:303)
        at org.apache.solr.common.util.JavaBinCodec.readVal(JavaBinCodec.java:283)
        at org.apache.solr.common.util.JavaBinCodec.unmarshal(JavaBinCodec.java:196)
        at org.apache.solr.client.solrj.request.JavaBinUpdateRequestCodec.unmarshal(JavaBinUpdateRequestCodec.java:131)
        at org.apache.solr.handler.loader.JavabinLoader.parseAndLoadDocs(JavabinLoader.java:122)
        at org.apache.solr.handler.loader.JavabinLoader.load(JavabinLoader.java:70)
        at org.apache.solr.handler.UpdateRequestHandler$1.load(UpdateRequestHandler.java:97)
        at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:82)
        at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:216)
        at org.apache.solr.core.SolrCore.execute(SolrCore.java:2637)
        at org.apache.solr.client.solrj.embedded.EmbeddedSolrServer.request(EmbeddedSolrServer.java:227)
        at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:214)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:177)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:138)
        at org.apache.solr.client.solrj.SolrClient.add(SolrClient.java:156)
        at net.yacy.cora.federate.solr.connector.SolrServerConnector.add(SolrServerConnector.java:213)
        at net.yacy.cora.federate.solr.connector.MirrorSolrConnector.add(MirrorSolrConnector.java:204)
        at net.yacy.search.index.Fulltext.putDocument(Fulltext.java:375)
        at net.yacy.search.index.Segment.putDocument(Segment.java:583)
        at net.yacy.search.index.Segment.storeDocument(Segment.java:666)
        at net.yacy.search.Switchboard.storeDocumentIndex(Switchboard.java:3505)
        at net.yacy.search.Switchboard.storeDocumentIndex(Switchboard.java:3419)
        at net.yacy.search.Switchboard.lambda$new$0(Switchboard.java:1057)
        at net.yacy.kelondro.workflow.InstantBlockingThread.job(InstantBlockingThread.java:72)
        at net.yacy.kelondro.workflow.AbstractBlockingThread.run(AbstractBlockingThread.java:82)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by Orbiter** [comment]
well that is a different bug, possibly caused by using the wrong libraries that solr is using. I downgraded guava from 31 to 25 because thats the correct dependency of solr 8.9.0
Hope it works...

**Comment by Scre13** [comment]
> well that is a different bug, possibly caused by using the wrong libraries that solr is using. I downgraded guava from 31 to 25 because thats the correct dependency of solr 8.9.0 Hope it works...

Thank you, looks good now 👍
