### ISSUE TITLE
Crawling from Sitemap URL breaks with java.io.IOException: Attempted read from closed stream. 

### ISSUE THREAD

**Issue by Scarfmonster** [yacy/yacy_search_server#500]
Running from the current git, sitemap indexing is broken. The error occurs both on compressed .xml.gz and uncompressed .xml sitemaps, with or without http compression.
A lot changed between 1.924/10069 and now, so I'm unsure where to look.

```
W 2022/09/16 21:39:35 ConcurrentLog * java.io.IOException: Attempted read from closed stream.
java.io.IOException: Attempted read from closed stream.
at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:165)
at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:238)
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:122)
at java.io.FilterInputStream.read(FilterInputStream.java:83)
at net.yacy.kelondro.io.ByteCountInputStream.read(ByteCountInputStream.java:89)
at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2890)
at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:674)
at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:148)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:806)
at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:121)
at net.yacy.document.parser.sitemapParser$SitemapReader.run(sitemapParser.java:159)
I 2022/09/16 21:39:34 SitemapReader * loading sitemap from https://wydarzenia.interia.pl/sitemap/wydarzenia.interia.pl-siteindex-9.xml.gz
I 2022/09/16 21:39:34 SITEMAP * Start parsing sitemap file https://wydarzenia.interia.pl/sitemap/wydarzenia.interia.pl-siteindex-9.xml.gz
```

**Comment by frankenstein91** [comment]
did you check other sitemaps too?
I see problems with the sitemap from you log on https://www.xml-sitemaps.com/validate-xml-sitemap.html

**Comment by Orbiter** [comment]
this is a gzip-ed sitemap which the validator does not recognize. but gzip-ed sitemaps are valid and they had been parseable in the past. I tried this crawl and I can reconstruct the problem. ..to be fixed..

**Comment by okybaca** [comment]
the same error happens with non .gziped sitemaps as well:

```
I 2023/11/14 02:31:03 SITEMAP * Start parsing sitemap file https://a2larm.cz/sitemap.xml
I 2023/11/14 02:31:03 SitemapReader * loading sitemap from https://a2larm.cz/sitemap.xml
W 2023/11/14 02:31:06 ConcurrentLog * java.io.IOException: Attempted read on closed stream.
java.io.IOException: Attempted read on closed stream.
        at org.apache.http.conn.EofSensorInputStream.isReadAllowed(EofSensorInputStream.java:107)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:116)
        at java.base/java.util.zip.CheckedInputStream.read(CheckedInputStream.java:60)
        at java.base/java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:267)
        at java.base/java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:259)
        at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
        at org.apache.http.client.entity.GZIPInputStreamFactory.create(GZIPInputStreamFactory.java:61)
        at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:51)
        at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:57)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:83)
        at net.yacy.kelondro.io.ByteCountInputStream.read(ByteCountInputStream.java:89)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.readAndBuffer(XMLEntityManager.java:3024)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:704)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:860)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:246)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
        at net.yacy.document.parser.sitemapParser$SitemapReader.run(sitemapParser.java:159)
```

this sitemap.xml seems to be valid, according to https://www.xml-sitemaps.com/validate-xml-sitemap.html

**Comment by Orbiter** [comment]
I made an attempt to fix this with https://github.com/yacy/yacy_search_server/commit/cff0991d850123dd5b9a7062b6df991c50fb26f5
However, I was not actual able to test this. I removed the usage of ByteCountInputStream because I don't see actual a use for this class here. the code should also better recognize gzipped files. With some good luck this works. Otherwise I have to actual debug that code...

**Comment by okybaca** [comment]
Great, thanks, I'll test it and let ya know!

**Comment by okybaca** [comment]
unfortunately, not working :-( 
error still the same:

```
W 2023/11/15 10:39:10 ConcurrentLog * java.io.IOException: Attempted read on closed stream.
java.io.IOException: Attempted read on closed stream.
        at org.apache.http.conn.EofSensorInputStream.isReadAllowed(EofSensorInputStream.java:107)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:116)
        at java.base/java.util.zip.CheckedInputStream.read(CheckedInputStream.java:60)
        at java.base/java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:267)
        at java.base/java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:259)
        at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
        at org.apache.http.client.entity.GZIPInputStreamFactory.create(GZIPInputStreamFactory.java:61)
        at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:51)
        at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:57)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.readAndBuffer(XMLEntityManager.java:3024)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:704)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:860)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:246)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
        at net.yacy.document.parser.sitemapParser$SitemapReader.run(sitemapParser.java:158)
```

**Comment by Orbiter** [comment]
I tried to debug this, but the sitemap https://a2larm.cz/sitemap.xml is really hard to get; I have often a time-out, just by loading the page with the browser.

**Comment by Orbiter** [comment]
I now have made a patch in https://github.com/yacy/yacy_search_server/commit/4a611ac6a39fca86f4b4d1108a5ffa403c8f3d31 where I first read the input stream of the sitemap fully and then use a buffer to actually parse the xml. For https://wydarzenia.interia.pl/ this worked.

**Comment by okybaca** [comment]
works great with everything i tested (bbc.co.uk, dw.com, ...), both plain and gziped!
ha, seems to be solved!
hooray! 
thanks, @Orbiter!
