### ISSUE TITLE
I have one THREAD WITH STATES: BLOCKED on 3 out of 4 servers. Minor

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#502]
THREADS WITH STATES: BLOCKED
 
Thread= qtp1002400446-153-acceptor-0@2cd60f64-httpd:8092@5434e40c{HTTP/1.1, (http/1.1)}{0.0.0.0:8092} id=153 BLOCKED
at sun.nio.ch.ServerSocketChannelImpl.accept(Unknown Source)
at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:388)
at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:702)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:773)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:905)
at java.lang.Thread.run(Unknown Source)
``
The server that does not have the error it is running Ubuntu 18.04  on an old I7 12 GB desktop openjdk version "11.0.16" 2022-07-19.
The server that does have it is running windows 11 on an old I7 16 GB notebook. Java jre-8u341
The server that does have it is Ubuntu 20.04 on an old I5 8GB notebook. Java 8
openjdk version "1.8.0_342"
OpenJDK Runtime Environment (build 1.8.0_342-8u342-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.342-b07, mixed mode)
The server that does have it is windows 11  on an old I5 4GB notebook. Java jre-8u341

I have tried increasing the JVM but still the same blocked thread.

I have copied Yacy v1.925/9749 and built it then pushed to to a separate repo at [https://github.com/smokingwheels/YaCy](https://github.com/smokingwheels/YaCy)
I have added some extra java arguments to the start up files.
Works for windows and linux.

I have searched this error but not really sure what I am actually doing or will it apply.
[https://stackoverflow.com/questions/28703777/jetty-acceptor-threads-blocked](https://stackoverflow.com/questions/28703777/jetty-acceptor-threads-blocked)

There is a comment.
Yes. We resolved the problem. The problem was internal dead locks. The code had some Synchronized blocks that was causing the request pool to exhaust. That was the issue in my case.

**Comment by smokingwheels** [comment]
Java 11 Fixes this error on windows.
See [https://github.com/smokingwheels/YaCy](https://github.com/smokingwheels/YaCyl)
