### ISSUE TITLE
Having trouble Upgrading runs ok fresh install.

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#519]
Ubuntu 18.04
Java 11
Looked up maybe need java 8 installed.

`W 2022/10/06 06:46:23 ConcurrentLog * java.lang.ClassNotFoundException: com.apple.eawt.Application
java.lang.ClassNotFoundException: com.apple.eawt.Application
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at net.yacy.gui.Tray.<clinit>(Tray.java:157)
	at net.yacy.search.Switchboard.<init>(Switchboard.java:364)
	at net.yacy.yacy.startup(yacy.java:215)
	at net.yacy.yacy.main(yacy.java:832)
I 2022/10/06 06:46:23 UPNP * found device: Archer_VR300
I 2022/10/06 06:46:23 UPNP * mapped mapped port 8090 to port 49169 on device Archer_VR300`

**Comment by smokingwheels** [comment]
Java 8
same error.
solr got upgrade maybe this caused it. 
Have another peer to try. export/import

**Comment by smokingwheels** [comment]
Did the  export/import ok with new install.
