### ISSUE TITLE
Block Threads Causes crawler to load 2 blocked file types. Slows crawling. 

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#528]
Block Threads Causes crawler to load 2 blocked file types. Slows crawling. 

Crawling 100 sites depth 2
Ubuntu 18.04 Java 11
Fresh install yacy.init using Deny types `iso,apk,dmg,zip,mp4,mp3,pdf,rpm,webm,deb,exe,gz,sql,exe,msi,dll`
Restart fixes it.

`YaCy Version: yacy_v1.926_202210060010_32e6a5f90
Assigned   Memory = 3728736256
Used       Memory = 561394000
Available  Memory = 3167342256
 
 
this thread dump function can find threads that lock others, to enable this function start YaCy with 'startYACY.sh -l'
 
THREADS WITH STATES: BLOCKED
 
Thread= qtp261650860-106-acceptor-1@67d1d05f-httpd:8090@7bf9b098{HTTP/1.1, (http/1.1)}{0.0.0.0:8090} id=106 BLOCKED
at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:232)
at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:388)
at org.eclipse.jetty.server.AbstractConnector$Acceptor.run(AbstractConnector.java:702)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
at java.lang.Thread.run(Thread.java:750)

 
Thread= BusyThread CrawlQueues.coreCrawlJob daemon id=96 BLOCKED
at net.yacy.crawler.robots.RobotsTxt.getEntry(RobotsTxt.java:164) [synchronized (syncObj) {]
at net.yacy.crawler.robots.RobotsTxt.getEntry(RobotsTxt.java:126)
at net.yacy.crawler.data.Latency.waitingRobots(Latency.java:126)
at net.yacy.crawler.data.Latency.waitingRemaining(Latency.java:217)
at net.yacy.crawler.data.Latency.getDomainSleepTime(Latency.java:286)
at net.yacy.crawler.HostQueue.pop(HostQueue.java:491)
at net.yacy.crawler.HostBalancer.pop(HostBalancer.java:490)
at net.yacy.crawler.data.NoticedURL.pop(NoticedURL.java:333)
at net.yacy.crawler.data.NoticedURL.pop(NoticedURL.java:283)
at net.yacy.crawler.data.CrawlQueues.coreCrawlJob(CrawlQueues.java:331)
at net.yacy.search.Switchboard$10.jobImpl(Switchboard.java:1182)
at net.yacy.kelondro.workflow.InstantBusyThread.job(InstantBusyThread.java:64)
at net.yacy.kelondro.workflow.AbstractBusyThread.run(AbstractBusyThread.java:215)

 `

**Comment by smokingwheels** [comment]
Maybe remote DNS or [@minitool_](https://twitter.com/minitool_)
 qt5.....causing constant slow HDD read with no write.
I uninstalled free soft..
I have been flattening **windows disk que time/length** for a few hours now. Also intermittently for 1 day..

I have not seen JVM over 600 mb when crawling.
Atm its using ~420 mb ~250 ppm. Average.

I had a clue when I had a crawler blocked thread, but I clicked again and the thread dump file overwrites.









 

[@yacy_search](https://twitter.com/yacy_search)
 = blocked thread. 
[@Nextclouders](https://twitter.com/Nextclouders)
 
[@PiholeS](https://twitter.com/PiholeS)
