### ISSUE TITLE
Two persisting nasty bugs - XML reader and default password

### ISSUE THREAD

**Issue by okybaca** [yacy/yacy_search_server#602]
Hi, 
since they are buried in the Issues clutter, I wanted to remind two realy nasty bugs, unresolved for many months. 
(Who admins the github repository? Would it be possible to clean the issues a little, close the inappropriate issues, label the useful ones and set some priorities? Can I or anyone help?)

First one is **broken XML import #500**:
YaCy is not able to parse the sitemaps.xml anymore and it fails with and error. Which breaks the crawling proces seriously.

Error thrown:
```

java.io.IOException: Attempted read on closed stream.
java.io.IOException: Attempted read on closed stream.
        at org.apache.http.conn.EofSensorInputStream.isReadAllowed(EofSensorInputStream.java:107)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:116)
        at java.base/java.util.zip.CheckedInputStream.read(CheckedInputStream.java:60)
        at java.base/java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:267)
        at java.base/java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:259)
        at java.base/java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:80)
        at java.base/java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:92)
        at org.apache.http.client.entity.GZIPInputStreamFactory.create(GZIPInputStreamFactory.java:61)
        at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:51)
        at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:57)
        at java.base/java.io.FilterInputStream.read(FilterInputStream.java:83)
        at net.yacy.kelondro.io.ByteCountInputStream.read(ByteCountInputStream.java:89)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.readAndBuffer(XMLEntityManager.java:3024)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:704)
        at java.xml/com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:150)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:860)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:824)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:246)
        at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
        at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:122)
        at net.yacy.document.parser.sitemapParser$SitemapReader.run(sitemapParser.java:159)
```

May be related, "Dump Reader for MediaWiki dumps" doesn't work either, even with the file given as an example. No error thrown.

Second nasty bug is a real YaCy usage stopper, #544. **In a fresh install, after entering the Administration and with no admin password entered, error is thrown**:

```
Ops!

Message: /usr/home/yacy/yacy/htroot/ConfigBasic.html
javax.servlet.ServletException: /usr/home/yacy/yacy/htroot/ConfigBasic.html
	at net.yacy.http.servlets.YaCyDefaultServlet.handleTemplate(YaCyDefaultServlet.java:886)
	at net.yacy.http.servlets.YaCyDefaultServlet.doGet(YaCyDefaultServlet.java:307)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:554)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:772)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1440)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:505)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1355)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at net.yacy.http.CrashProtectionHandler.handle(CrashProtectionHandler.java:33)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:487)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:732)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:479)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
	at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
	at java.base/java.lang.Thread.run(Thread.java:829)

```
Setting the password method described in [README](https://github.com/yacy/yacy_search_server/blob/master/README.md): 
'The default admin account name is admin and the default password is yacy. Please change it after installation using the http://<server-address>:8090/ConfigAccounts_p.html service.' doesn't work either, because admin password 'yacy' is not accepted by default installation.

As a result, YaCy is broken in the default installation and no clue is provided in the basic documentation.

The security question is, whether YaCy _should_ be working with no admin password set, or chosing the password would be compulsory after installation.

Does anyone have any clue, how to solve these two nasty bugs?

**Comment by Orbiter** [comment]
We had the strange idea in the past that after a unknown time (yes we randomized that) the admin interfaces locks itself with a random password.

The reason was that setting a default password was considered to be insecure. While this is true, it is also unusable because it frustrates users and prevents a growth of users.

I would prefer the following behavior:
- the default account is always admin:yacy
- the access from localhost is always possible without login.

**Comment by Orbiter** [comment]
@okybaca I admit that organizing the issues has grown over my head. If you like you may help me out if you want. I invited you to triage rights on the issues so you should also be able to close them.

**Comment by okybaca** [comment]
Thanks, I will try!

**Comment by okybaca** [comment]
I tried to label most of the Issues and closed some outdated. What I suggest is to add three new labels: "index", "search" and "network" to sort out the problems more granularly (since "crawler" and "sitemap" exist). It seems I don't have the right to add labels.

**Comment by Orbiter** [comment]
Ok, now with commits https://github.com/yacy/yacy_search_server/commit/4da320bebfca4412a17cd7587ae1c16780ff210b https://github.com/yacy/yacy_search_server/commit/2c60ff14bb275580aa94119e898b7df7ae023356 and https://github.com/yacy/yacy_search_server/commit/4308aa5415c0c2aadbada8ac083c71cfb0001d1b I believe to have the issue with the default password fixed. It was a bit complex, because I had also to remove the concept of no-password-is-default-password.

**Comment by okybaca** [comment]
#500 solved as well, thanks, @Orbiter!

Don't see any disastrous bug now, maybe it's ripe for release!
