### ISSUE TITLE
Blocked thread when searching. on Windows

### ISSUE THREAD

**Issue by smokingwheels** [yacy/yacy_search_server#658]
Likely to be lack of memory.
Running on windows 11 amazon java 11.
 
THREADS WITH STATES: BLOCKED
 
'Thread= RemoteSearch.solrRemoteSearch("xcfo" to NmWgZ0aELTlt) id=14655 BLOCKED
at java.base@11.0.24/java.lang.Thread.join(Thread.java:1308)
at app//net.yacy.peers.Protocol.solrQuery(Protocol.java:1259)
at app//net.yacy.peers.RemoteSearch$2.run(RemoteSearch.java:411)'

also trying this.
set javacmd=%javacmd% -Djava.awt.headless=true -Dsolr.directoryFactory=solr.MMapDirectoryFactory -Dfile.encoding=UTF-8 -Dserver -DUseG1GC -DMaxGCPauseMillis=100 -DUseConcMarkSweepGC -DCMSIncrementalPacing

**Comment by smokingwheels** [comment]
I increased memory and have been crawling FTP sites.
Yacy is very slow to respond but it is still working.

YaCy Version: yacy_v1.940_202408262308_6db374fdc
Assigned   Memory = 31457280000
Used       Memory = 1304150224
Available  Memory = 30153129776
 
 
THREADS WITH STATES: BLOCKED
 
Thread= commitScheduler-22-thread-1 id=339 BLOCKED
at java.base@11.0.24/java.lang.Thread.yield(Native Method)
at app//org.apache.lucene.store.ByteBufferGuard.invalidateAndUnmap(ByteBufferGuard.java:76)
at app//org.apache.lucene.store.ByteBufferIndexInput.close(ByteBufferIndexInput.java:494)
at app//org.apache.lucene.store.BufferedChecksumIndexInput.close(BufferedChecksumIndexInput.java:57)
at app//org.apache.lucene.codecs.lucene90.Lucene90NormsProducer.<init>(Lucene90NormsProducer.java:80)
at app//org.apache.lucene.codecs.lucene90.Lucene90NormsFormat.normsProducer(Lucene90NormsFormat.java:96)
at app//org.apache.lucene.index.IndexingChain.flush(IndexingChain.java:293)
at app//org.apache.lucene.index.DocumentsWriterPerThread.flush(DocumentsWriterPerThread.java:386)
at app//org.apache.lucene.index.DocumentsWriter.doFlush(DocumentsWriter.java:497)
at app//org.apache.lucene.index.DocumentsWriter.flushAllThreads(DocumentsWriter.java:676)
at app//org.apache.lucene.index.IndexWriter.getReader(IndexWriter.java:568)
at app//org.apache.lucene.index.StandardDirectoryReader.doOpenFromWriter(StandardDirectoryReader.java:380)
at app//org.apache.lucene.index.StandardDirectoryReader.doOpenIfChanged(StandardDirectoryReader.java:365)
at app//org.apache.lucene.index.DirectoryReader.openIfChanged(DirectoryReader.java:246)
at app//org.apache.solr.core.SolrCore.openNewSearcher(SolrCore.java:2306)
at app//org.apache.solr.core.SolrCore.getSearcher(SolrCore.java:2559)
at app//org.apache.solr.update.DirectUpdateHandler2.commit(DirectUpdateHandler2.java:770)
at app//org.apache.solr.update.CommitTracker.run(CommitTracker.java:280)
at java.base@11.0.24/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base@11.0.24/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@11.0.24/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base@11.0.24/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base@11.0.24/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base@11.0.24/java.lang.Thread.run(Thread.java:829)


ChatGPT recommends.
-XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:G1HeapRegionSize=16m

**Comment by smokingwheels** [comment]
I had an attempt to solve this issue. with both chatGPT's
HostQueue.java line 434
HttpClient.java  line 835
RobotsTxt.java line 164
SolrServerConnector.java line 149

no luck as yet
