### ISSUE TITLE
Http error 500 on News and Wiki

### ISSUE THREAD

**Issue by ainslied** [yacy/yacy_search_server#87]
Hello,

In a fresh install of Yacy and Debian Jessie I got HTTP ERROR 500 for these pages of Administration > System Status > Messages & Community Data :
    Overview    Incoming    Processed    Outgoing    Published (/News.html)
    Local Peer Wiki (/Wiki.html)
For information, Yacy use case is "Search portal for your own web pages" for the moment.
May be it's normal because I have not configured anything but I'm not sure it is the waited behaviours.

The error message is :

HTTP ERROR 500
Problem accessing /News.html. Reason:
    Server Error
Caused by:
javax.servlet.ServletException: /usr/share/yacy/htroot/News.html
    at net.yacy.http.servlets.YaCyDefaultServlet.handleTemplate(YaCyDefaultServlet.java:850)
    at net.yacy.http.servlets.YaCyDefaultServlet.doGet(YaCyDefaultServlet.java:316)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:542)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at net.yacy.http.CrashProtectionHandler.handle(CrashProtectionHandler.java:33)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:499)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
YaCy 1.90 - powered by Jetty -

**Comment by luccioman** [comment]
Hello @ainslied thank you for reporting. 
It looks like this error occurs when your peer can not be reached from outside : I reproduce it on my peer (version 1.91/9301) when the internet connection is down. You also probably have either "You have not published your peer seed yet..." or even "The peer must go online to get a peer address" messages on your /Status.html page.
There is definitely something to fix on the News.html and Wiki.html pages to handle properly this case, but I also suggest you to check that your peer is reachable from the others.

Best regards

**Comment by luccioman** [comment]
Commit https://github.com/yacy/yacy_search_server/commit/2da5f339f82ae7b54932f8aa0fb4c7b94d5ee007 fixes the issue for the reported pages but other ones like /Blog.html are still to check and eventually to fix for the described cases. Theses pages basically correspond to the deprecated use of Seed.getIP() (see also issue #50 ).

**Comment by luccioman** [comment]
This issue and other found similar error cases are now fixed.
Any feedback is welcome of course!
